name: Site Visit Reminder

on:

  schedule:

    - cron: '0 7 * * *'
    - cron: '30 8 * * *'
    - cron: '0 10 * * *'
    - cron: '30 11 * * *'
    - cron: '0 13 * * *'
    - cron: '0 16 * * *'
    - cron: '30 17 * * *'

  workflow_dispatch:

jobs:

  notify:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Send Notification

        run: |

          curl -X POST \
          "${{ secrets.NOTIFY_ENDPOINT }}"
